name: "general-stdio-grader"
description: "General Std I/O Grader"
author: "DKU-IRDM-Classroom"

inputs:
  time-limit:
    required: false
    default: 2
  memory-limit:
    required: false
    default: '256m'
  output-limit:
    required: false
    default: 1048576
  total:
    required: true

permissions:
  contents: read
  actions: read
  checks: write

runs:
  using: "composite"
  steps:

    - name: 빌드 준비
      id: prepare
      shell: bash
      run: |
        : 빌드 준비
        set -euo pipefail

        command -v docker >/dev/null
        docker pull -q gcc:13 >/dev/null

    - name: 빌드
      id: build
      shell: bash
      run: |
        : 빌드
        set -euo pipefail

        if [ ! -f ./main.c ]; then
          echo "액션 오류: main.c 파일 없음"
          exit 2
        fi

        cp ./main.c "$HOME/workdir/"

        docker run --rm \
          --pull=never \
          --network none \
          --cpus "1.0" \
          --memory "${{ inputs.memory-limit }}" \
          --memory-swap "${{ inputs.memory-limit }}" \
          --pids-limit "128" \
          --cap-drop ALL \
          --security-opt no-new-privileges \
          --tmpfs /tmp:rw,nosuid,nodev,noexec,size=64m \
          -u "$(id -u):$(id -g)" \
          -v "$HOME/workdir":/workdir \
          -w /workdir \
          gcc:13 \
          bash -lc 'set -euo pipefail; gcc -O2 -std=c17 -o main main.c'

    - name: fail
      id: fail
      if: ${{ steps.build.outcome != 'success' }}
      shell: bash
      run: |
        : 빌드 실패
        set -euo pipefail

        PASS=0
        TOTAL="${{ inputs.total }}"

        echo "Points ${PASS}/${TOTAL}"

    - name: grade
      id: grade
      if: ${{ steps.build.outcome == 'success' }}
      shell: bash
      run: |
        : 채점
        set -euo pipefail

        PASS=0
        TOTAL="${{ inputs.total }}"

        for n in $(seq 1 ${TOTAL}); do

          set +e
          timeout --signal=KILL ${{ inputs.time-limit }}s \
          docker run --rm \
            --network none \
            --cpus "1.0" \
            --memory "${{ inputs.memory-limit }}" \
            --memory-swap "${{ inputs.memory-limit }}" \
            --pids-limit "128" \
            --cap-drop ALL \
            --security-opt no-new-privileges \
            --tmpfs /tmp:rw,nosuid,nodev,noexec,size=64m \
            -u "$(id -u):$(id -g)" \
            -v "$HOME/workdir":/workdir \
            -w /workdir \
            -e n="$n" \
            gcc:13 \
            bash -lc '/workdir/main < "/workdir/${n}.in" > "/workdir/${n}.out"'
          RC=$?
          set -e

          if [ ${RC} -eq 124 ]; then
            echo "[케이스 ${n}] 시간 초과 (TLE)"; continue
          elif [ ${RC} -eq 137 ]; then
            echo "[케이스 ${n}] 메모리 초과 (MLE)"; continue
          elif [ ${RC} -ne 0 ]; then
            echo "[케이스 ${n}] 실행 오류 (RE)"; continue
          fi
          BYTES=$(stat -c%s "$HOME/workdir/${n}.out")
          if [ "$BYTES" -gt ${{ inputs.output-limit }} ]; then
            echo "[케이스 ${n}] 출력 초과 (OLE)"; continue
          fi

          set +e
          python3 \
            "${{ github.action_path }}/compare.py" \
            "$HOME/workdir/${n}.ans" \
            "$HOME/workdir/${n}.out"
          CMP=$?
          set -e

          if [ $CMP -eq 0 ]; then
            echo "[케이스 ${n}] 정답 (AC)"; PASS=$((PASS+1))
          elif [ $CMP -eq 1 ]; then
            echo "[케이스 ${n}] 오답 (WA)"
          elif [ $CMP -eq 2 ]; then
            echo "[케이스 ${n}] 형식 오류 (PE)"
          else
            echo "[케이스 ${n}] 내부 오류 (IE)"
          fi

        done

        echo "Points ${PASS}/${TOTAL}"

        {
          echo "GRADE_RESULTS<<EOF"
          echo "{\"name\":\"grade result\",\"score\":$PASS,\"max_score\":$TOTAL,\"output\":\"Points $PASS/$TOTAL\"}"
          echo "EOF"
        } > result.json
        echo "result=$(cat result.json)" >> "$GITHUB_OUTPUT"

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADE_RESULTS: "${{ steps.grade.outputs.result }}"
      with:
        runners: grade
